language: node_js
node_js: 7

env:
  - CXX=g++-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

install: npm install

script:
  - npm run build

cache:
  directories:
    - node_modules
  
notifications:
    email: false
